### ISSUE TITLE
is_insert_char seems to be redundant

### ISSUE THREAD

**Issue by Kixunil** [kneasle/sapling#24]
I wanted to take a look at cleaning up that [nesting in `editor.rs`](https://github.com/kneasle/sapling/blob/288c5a08f47f64a9b52d384acbddf81873745081/src/editor.rs#L356) and it seems to me that `is_insert_char` is not really needed as the following two functions essentially do the same check (or if they don't, they should).

But I'm not entirely sure, maybe I'm missing something. So I thought you may know the answer quicker than I can analyze it completely.

**Comment by kneasle** [comment]
Oh they do as well! I had not spotted that.  The refactoring that I was thinking of was that we should probably push all the code currently causing the nesting down the current 'call stack' of `Editor -> DAG -> Ast`.  It makes no sense at all that new nodes are created by `Editor` - we may as well pass just a `char` down to `DAG` and receive a `Result` back.  This would mean we could inline a lot of the code in `editor::Editor` and simplify things a lot.

Thinking about it, though, I'm pretty sure the current setup of how nodes are added is not ideal in many ways - the biggest issue that springs to mind is that it doesn't allow implementors of `Ast` the necessary context to properly prevent errors (such as replacing the key of a JSON object field with something other than a string).

**Comment by Kixunil** [comment]
I actually kinda like the current way of making node separately because it forces the implementors to properly divide the code into functions. :D It also seems to avoid duplication of logic.

My thinking was to have a new error type for the editor and return `Result` from editor operations.

**Comment by kneasle** [comment]
> I actually kinda like the current way of making node separately because it forces the implementors to properly divide the code into functions. :D It also seems to avoid duplication of logic.

Me too, though I'd rather all that functionality happen in `editable_tree::DAG` (since the point of `editable_tree::DAG` is to provide a simple interface so that `Editor` only has to deal with interacting with the user).

It does have a few issues that could do with being ironed out...  The main one is that sometimes one insert operation could result in multiple nodes being added (suppose I want to add `true` to an empty object, i.e. `{}` -> `{"": true}`), but I think this could be fixed by passing the arena to `Ast::from_char`, so that extra nodes can be allocated if needed.  This seems a bit ugly since it means that `Ast` has to know about the existence of the `Arena`, but I don't see how that can be avoided.

> My thinking was to have a new error type for the editor and return `Result` from editor operations.

Yes - this definitely sounds like a better design pattern.  But I currently think it's better to move all the editing methods into `DAG` and have them return custom error types, which `Editor` can then log or handle separately.  So for example, `Editor::delete_cursor` will be implemented as:
```rust
impl Editor {
  fn delete_cursor(&mut self) -> {
    if let Err(e) = self.tree.delete_cursor() {
      log::warn!("{}", e);
    }
  }
}

impl DAG {
  pub fn delete_cursor(&mut self) -> Result<(), SomeErrorType> {
    ...
  }
}
```

These new tiny functions could just be inlined straight into the match arms for `Action` [here](https://github.com/kneasle/sapling/blob/288c5a08f47f64a9b52d384acbddf81873745081/src/editor.rs#L549), and clear up `Editor` a lot.

**Comment by Kixunil** [comment]
> `Ast` has to know about the existence of the `Arena`, but I don't see how that can be avoided.

Yeah, I figured that out before as well. `Arena` at least can be abstracted I think.

Anyway, your design suggestion makes sense. I'd even go further and write `ResultExt` trait that has `log_edit_error()` method.

**Comment by kneasle** [comment]
I'm not convinced that abstracting the `Arena` is necessary - it's an integral part of `Ast` anyway due to the type annotations.  It also only has one public method [`Arena::alloc`](https://github.com/kneasle/sapling/blob/master/src/arena.rs#L44) so it's pretty much abstracting itself.

I really like the idea of `ResultExt` (perhaps with a different name like `EditResult`).  It would then streamline [the match statement](https://github.com/kneasle/sapling/blob/288c5a08f47f64a9b52d384acbddf81873745081/src/editor.rs#L549) in `Editor` to (for example):
```rust
match action {
    ...
    Action::Replace(c) => self.tree.replace_cursor(c).write_log(),
    ...
    Action::Undo => self.tree.undo().write_log(),
    Action::Redo => self.tree.redo().write_log(),
    ...
}
```
where `write_log()` would write a `debug` log of a successful edit, or an `warning` log of the error otherwise. 

Or we could just use error handling and make the fuction that executes commands return `Box<dyn EditResult>`, so that all `write_log()`s could be turned into `?`s.

**Comment by Kixunil** [comment]
I meant abstracting when crossing plugin boundary.

> perhaps with a different name like `EditResult`

`ResultExt` is considered idiomatic name for this thing. But not quite sure why people behind the guidelines decided it's a good idea. Might be worth revisit.

> Or we could just use error handling and make the fuction that executes commands return `Box<dyn EditResult>`, so that all `write_log()`s could be turned into `?`s.

I was thinking about enums (I like to avoid allocations), but creating an enum just to match on it in the caller once seemed too much.

Another ridiculous hack that comes to my mind is doing this:

```rust
struct InsaneError;

impl<T: std::error::Error> From<T> for InsaneError {
    fn from(error: T) -> Self {
        log::warn!("Error during editing: {}", error);
        InsaneError
    }
}

fn execute_action(action: Action) -> Result<(), InsaneError> {
match action {
        ...
        Action::Replace(c) => self.tree.replace_cursor(c)?,
        ...
        Action::Undo => self.tree.undo()?,
        Action::Redo => self.tree.redo()?,
        ...
    }
}
Ok(())
```

**Comment by kneasle** [comment]
> I meant abstracting when crossing plugin boundary.

Ooooh OK - yes that makes sense.

> `ResultExt` is considered idiomatic name for this thing. But not quite sure why people behind the guidelines decided it's a good idea. Might be worth revisit.

Having clearly not read the guidance on this kind of thing, I think `ResultExt` (presumably a short-hand for `ResultExtension`?) is too general a name, whereas `EditResult` seems a more precise name.

> ```rust
> struct InsaneError;
> ```

This causes me pain :laughing:.

> I was thinking about enums (I like to avoid allocations), but creating an enum just to match on it in the caller once seemed too much.

Yeah so I thought that perhaps `DAG` could return a single result type from all of its edit functions, which could then be returned directly from `execute_action`, like:

```rust
pub enum EditResult {
    Ok(EditOk),
    Err(EditErr)
}

impl DAG<...> {
    ...
    pub fn replace_cursor(&mut self, c: char) -> EditResult { ... }
    ...
    pub fn undo(&mut self) -> EditResult { ... }
    pub fn redo(&mut self) -> EditResult { ... }
    ...
}

impl Editor<...> {
    fn execute_comand(&mut self, cmd: Command) -> EditResult {
        match command {
            Command::Undo => self.tree.undo(),
            Command::Redo => self.tree.redo(),
            ...
        }
    }

    fn mainloop(&mut self) {
        ...
        // Run a command and log the result in one place
        self.execute_command(cmd).log_result();
        ...
    }
}

**Comment by Kixunil** [comment]
> presumably a short-hand for `ResultExtension`

Correct. I'm also not confident this naming is really good idea. Name collisions could happen more easily for instance.

> This causes me pain

Yeah, there's a reason I named it `InsaneError` and not `VeryElegantSolutionToErrorHandling` :D

> Yeah so I thought that perhaps DAG could return a single result type from all of its edit functions, which could then be returned directly from execute_action, like:

Yeah, while I personally like the power of having each method define its type, it makes very little sense in this case. `Editor` is the one who dictates the rules of how editing should work, and so far there's not need to distinguish between error types. And if such need comes later, it will have to be a breaking change anyway - separating the error types won't help us at all.

So I believe this is the best design, at least now.

**Comment by Kixunil** [comment]
Interesting, now that I'm trying to find the explicit guidelines I can't find it anywhere. I only found https://github.com/rust-lang/api-guidelines/issues/146 which suggests the opposite.

**Comment by kneasle** [comment]
> Yeah, there's a reason I named it `InsaneError` and not `VeryElegantSolutionToErrorHandling` :D

To be honest, if someone asked me to review a PR with either of those names in it, I'd be instantly skeptical :laughing:. 

> So I believe this is the best design, at least now.

Me too.  I think I'll implement this design next stream...
