### ISSUE TITLE
Crash when insert an invalid char in array, and object

### ISSUE THREAD

**Issue by stokhos** [kneasle/sapling#68]
Insert invalid cha `c` in array and object will cause the problem.

This problem is related to cursor location. 
https://github.com/kneasle/sapling/blob/9fed519567bc7b8a7aa61fb56395edeb9cf7b6cc/src/editor/dag.rs#L410-L415
``

**Comment by kneasle** [comment]
This crashes regardless of which node is under the cursor.  I've found a fix, and I'm making regression tests for this.

**Comment by kneasle** [comment]
Actually, if #63 is fixed then this bug will not be possible.

**Comment by kneasle** [comment]
Oh whoops, this was accidentally closed because of some silly commit wording :laughing: who knew.

**Comment by kneasle** [comment]
I've been doing some digging, and the cause of the problem is that `Json::is_valid_child` returns a blanket `true` if the node being inserted into is `Json::Object` or `Json::Array`.  By extension, this also returns `true` for invalid characters, and so an error is not returned, and so `Json::from_char` is called and then unwrapped, causing the crash.

This will be fixed along with #63, because `Json::is_valid_child` will take a type-safe intermediate type and so it isn't possible to insert an invalid node.
