### ISSUE TITLE
Go to previous cursor location

### ISSUE THREAD

**Issue by stokhos** [kneasle/sapling#88]
Do you think it is necessary to have a key that moves cursor to previous cursor location?

Like, if the cursor is on array, and I accidentally pressed `p`, the cursor moved parent, and I will have to press `c` and `4j` to move back to the previous cursor location, this is very inconvenient
```json 
[
  true,
  false,
  false,
  { "key-1" : true, "key-2" : false },
]
```

**Comment by kneasle** [comment]
Hmm... yes this should probably be a thing - Vim as `^O`/`^I` for this.  I'm not sure of the best way to implement it, because we really don't want to undo the cursor over an edit without also undoing the edit - because doing so would probably move the cursor onto invalid nodes.

The best strategy would probably be to re-implement history as a sequence of either edits or cursor movements, and then have `u`/`^R` jump to the nearest _edit_ whilst `^O`/`^I` simply move back by a single step.  I think that long-run this is probably the most consistent and intuitive thing we could do.

**Comment by kneasle** [comment]
On closer inspection Vim doesn't have exactly this (`^O`/`^I` appear to do something else).  But I still agree that this would be a useful thing to have.

**Comment by stokhos** [comment]
I think this is not exactly similar to go to previous location in vim. 

I think what I wanted to say is we need a way go to previous child. Because for a big array, we might accidentally press `p` when we want to press 'c'

**Comment by kneasle** [comment]
Yeah it's super annoying - I get a similar thing when either using `gg`/`G` to jump to the top/bottom of a file or jumping to definition.  Apparently `^O` fixes the latter, but `gg` is very similar to accidentally pressing `p` inasmuch as it destroys information about the cursor location.

This is definitely needed (though I also think that `C` should jump to the last child, making this better in small cases).

**Comment by stokhos** [comment]
> This is definitely needed (though I also think that C should jump to the last child, making this better in small cases).

The char I picked is `C` LOL.

**Comment by kneasle** [comment]
I mean, keybindings don't matter very much IMO (especially for things that aren't in Vim) - we can just change them later if needed.

I have another idea for how to do this - perhaps `c` should move to the _last child we selected_ (instead of always moving to the _first-indexed_ child).  This is similar to how window switching in herbstuftwm (my current window manager) works, and it feels really nice.  It would be a bit more work, but giving us more work to make the users' lives easier is a completely valid trade-off IMO.

That being said, I still think being able to properly undo arbitrary cursor changes is needed (it would basically be a requirement for a multiple-cursor set-up).

**Comment by stokhos** [comment]
Agreed. 
I can try to implement the multi-cursor, and undo the cursor changes, I feel these two would be challenging to me. Is this ok?

**Comment by kneasle** [comment]
Multiple cursors is going to be really hard, and will likely take several large PRs to achieve - there needs to be a load of refactoring done to make the code ready to handle multiple cursors in a nice way.

Undoing cursor locations is definitely up for grabs, though, if you want it.

**Comment by stokhos** [comment]
First of all don't compromise your plan.
Then the answer is always yes. I'm really into complicated stuff. :p

**Comment by stokhos** [comment]
> should move to the _last child we selected_ (instead of always moving to the _first-indexed_ child).

What do you mean by selected over here?

**Comment by kneasle** [comment]
> What do you mean by selected over here?

Oh wait hold on by selected I mean 'under the cursor' - the two are kind of equivalent in my brain because the cursor decides what gets deleted and replaced, etc. 

So for every node in the tree, Sapling should remember which child of that node was last selected, and when the user presses `c` on that node it will move to the child it remembers, rather than the first index. Basically this will mean that pressing `p` then `c` will always put you back where you were. 

I'm not sure of a good way to handle this memory, though - because I don't think this data should be added directly to the `Ast` nodes, though this might be necessary. It would be much easier to just remember one 'last cursor index', so that pressing `p` once can be undone with `c`. However, this would make `cc` the opposite of `pp` but might be enough for now.

**Comment by stokhos** [comment]
> I'm not sure of a good way to handle this memory, though - because I don't think this data should be added directly to the `Ast` nodes, though this might be necessary.

You think add a hashmap to `Dag` to store the `Node` and last `Cursor` location would be a efficient way to solve the problem?
